export default {
  "login": "Edita-Pernaviene",
  "id": 68382071,
  "node_id": "MDQ6VXNlcjY4MzgyMDcx",
  "avatar_url": "https://avatars.githubusercontent.com/u/68382071?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Edita-Pernaviene",
  "html_url": "https://github.com/Edita-Pernaviene",
  "followers_url": "https://api.github.com/users/Edita-Pernaviene/followers",
  "following_url": "https://api.github.com/users/Edita-Pernaviene/following{/other_user}",
  "gists_url": "https://api.github.com/users/Edita-Pernaviene/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Edita-Pernaviene/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Edita-Pernaviene/subscriptions",
  "organizations_url": "https://api.github.com/users/Edita-Pernaviene/orgs",
  "repos_url": "https://api.github.com/users/Edita-Pernaviene/repos",
  "events_url": "https://api.github.com/users/Edita-Pernaviene/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Edita-Pernaviene/received_events",
  "type": "User",
  "site_admin": false,
  "name": 'Edita Pernaviene',
  "company": 'My Team',
  "blog": "https://app.netlify.com/teams/edita2per/overview",
  "location": "London",
  "email": null,
  "hireable": null,
  "bio": "HTML5, CSS3, Git, JavaScript, SQL, JSON, react",
  "twitter_username": null,
  "public_repos": 6,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2020-07-16T12:23:25Z",
  "updated_at": "2021-01-21T08:21:46Z"
};
